### DISCUSSION TITLE
how to have a persistent id for a device in docker

### DISCUSSION THREAD

**Discussion by ljmerza** [merbanan/rtl_433#2537] [General]
i run rtlamr and rtl433 on two different rtl devices via docker. the issue im having is the path to the device changes on every reboot so i have to modify the device path ever boot. rtlamr always uses the first device found so i know to always set rtl433 as the second device. here's my docker compose

```
rtlamr:
    image: allangood/rtlamr2mqtt
    devices:
      - /dev/bus/usb

  rtl433:
    image: hertzg/rtl_433:latest
    devices:
      - '/dev/bus/usb/001/006'
  ```

and here's my `lsusb`:

```
Bus 001 Device 007: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
Bus 001 Device 006: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
```

so the first device will always be picked up by rtlamr and the second device i have to change the `- '/dev/bus/usb/001/006'` part of the docker config every reboot. i cant seem to track down any ids for these devices or any other way to pass them down to docker and it be persistent on boot.
