### DISCUSSION TITLE
Wonderful Home Doorbell - Custom Protocol

### DISCUSSION THREAD

**Discussion by jimmejames** [merbanan/rtl_433#2835] [Show and tell]
I wanted to integrate a Wonderful Home D10 wireless doorbell into Home Automation setup and didn't find a step-by-step guide for my application, so sharing what I did in the hopes it helps someone else.  My device was not one of the readily available protocols, so I had to add a custom one.  I'm going to assume you have Home Automation running, a SDR radio, MQTT installed and configured, rtl_433 installed (as an Add-On) and configured (I used rtl_433 version 0.4.1 running HASS Core 2024.2.1 and OS 11.5 on a Raspberry Pi), and did a search to figure out the frequency of your transmitter.

I did not know what data (payload or format) of my transmitter, so first step was setting up a configuration file for rtl_433.  Using the File Editor Add-On in HA, I created a file here:  /homeassistant/rtl_433/rtl_Spa.conf.template with the following:
```
output kv

output mqtt://192.168.1.100:1883,user=<username>,pass=<password>

frequency 433875000
analyze_pulses true
```

Obviously you need to replace the <username> and <password> with your MQTT credentials and frequency with the particulars of your device.

Going to Settings -> Add-ons -> rtl_433 and Starting/Restarting, I was provided this line in a mix of a larger output on the Log tab:
```
[rtl_Spa] Use a flex decoder with -X 'n=name,m=OOK_PWM,s=172,l=564,r=1800,g=624,t=157,y=0'
[rtl_Spa] [01] {33} 14 8d df b9 80 : 00010100 10001101 11011111 10111001 1
```

 I then edited my /homeassistant/rtl_433/rtl_Spa.conf.template with File Editor as follows:
```
output kv

output mqtt://192.168.82.113:1883,user=<username>,pass=<password>

frequency 433875000

decoder {
    name=Wonderful_Home_Doorbell,
    modulation=OOK_PWM,
    short=156,
    long=548,
    reset=1832,
    gap=652,
    tolerance=157,
    match={33}0x148DDFB98
    unique,
}
```

Home Assistant, at that point, could 'see' the device if I told MQTT to 'Listen to a topic', but it wasn't yet an automation.  As my device was a simple binary 'button press' or 'button not pressed' signal, I started out trying to look at the data received in MQTT for a match to my expected String (14 8d df b9 80), but found that parsing the JSON data was frustrating as I couldn't be guaranteed any particular row of data would have my String.  Fortunately, as my device only sent a signal when the button was pressed, I didn't care about times it wasn't pressed, so I scratched looking at the data field and only looked at the time stamp for my automation.

In other words, I created a Sensor in a *.yaml file:
```
mqtt:
  sensor:
     - name: "Spa Doorbell Time"
       state_topic: "rtl_433/+/events/#"
       value_template: "{{ value_json.time }}"
```

And then I created an Automation that sends a notice to my cell when the time stamp of the door bell changes (in other words, when someone presses the button):

```
alias: Spa_Doorbell
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.spa_doorbell_time
    id: Doorbell_State_Change_Trigger
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ states('sensor.spa_doorbell_time') != 'unknown' }}"
      - condition: template
        value_template: "{{ states('sensor.spa_doorbell_time') != 'unavailable' }}"
      - condition: template
        value_template: "{{ trigger.from_state != trigger.to_state}}"
      - condition: template
        value_template: "{{ trigger.to_state != 'unavailable'}}"
      - condition: template
        value_template: "{{ trigger.to_state != 'unknown'}}"
action:
  - service: notify.mobile_app_your_device
    metadata: {}
    data:
      title: Spa Needs Attention
      message: Check Spa
mode: single
```

Pitfalls and complications:

1. I did my original capture and decoding on a non-production SDR and found the values I eventually plugged into my rtl_433 configuration file different.  Different enough, in fact, that the capture (done on an official RTL_SDR v4) did not work on my production SDR (official RTL_SDR v3).
2. There can be a couple minute delay after restarting HA (after any messages about "not everything will be available yet") for my SDR to start responding to signals.  Time consuming to wait a few minutes after changes, but if you find you're not getting responses in HA, perhaps wait a few minutes and try sending the signal to the SDR again.

Edit 3/8/24:  I had an issue where I'd periodically catch a neighbor's signal so I tweaked the Home Assistant automation to be more robust.  Is it overkill?  Don't know- been working about a month without issue.
