### DISCUSSION TITLE
Cannot get multiple devices working with serial #

### DISCUSSION THREAD

**Discussion by gcormier** [merbanan/rtl_433#2994] [Q&A] [answered]
I have two RTLSDR's on my machine.

```
$ rtl_eeprom -d 0
Found 2 device(s):
  0:  Generic RTL2832U OEM
  1:  Generic RTL2832U OEM

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner

Current configuration:
__________________________________________
Vendor ID:              0x0bda
Product ID:             0x2838
Manufacturer:           Realtek
Product:                RTL2838UHIDIR
Serial number:          433
Serial number enabled:  yes
IR endpoint enabled:    yes
Remote wakeup enabled:  no
__________________________________________
```

You can see I have set the serial number. However, if I try to use this with rtl_433, it does not work.

```
rtl433:
    container_name: rtl433
    #image: hertzg/rtl_433:latest
    image: hertzg/rtl_433:latest-debian
    environment:
      - TZ=America/Toronto
    devices:
      - /dev/bus/usb
    command:
      - "-d"       # RTL device with serial 433
      - ":433"
      - "-R 176:12080"  # Blueline
      - "-R 40"         # Accurite Weatherstation
```

Logs:
```
19:32 $ dc up rtl433
[+] Running 1/0
 ✔ Container rtl433  Created                                                                                                                                             0.0s 
Attaching to rtl433
rtl433  | rtl_433 version 23.11 branch  at 202311281352 inputs file rtl_tcp RTL-SDR SoapySDR with TLS
rtl433  | MQTT: Publishing MQTT data to 192.168.1.33 port 1883
rtl433  | MQTT: Publishing device info to MQTT topic "rtl_433[/model][/subtype][/channel][/id]".
rtl433  | SDR: Could not find device with serial '433' (err -3)
rtl433 exited with code 0
```

Any ideas?
