### DISCUSSION TITLE
Frequency Hopping & Demod Modes

### DISCUSSION THREAD

**Discussion by jhkubs** [merbanan/rtl_433#3208] [Q&A] [answered]
Hello, looking for some help setting up frequency hopping between 433M and 915M. Apologies in advance if this topic has already been discussed somewhere, I've been searching for a few weeks and found this reddit post from 2 years ago: https://www.reddit.com/r/RTLSDR/comments/13kbtec/rtl_433_frequency_hopping/, and this related discussion about switching sampling rates on hop: https://github.com/merbanan/rtl_433/discussions/3069

I'm attempting to poll two sensors, an 592TXR at 433Mhz, and a WS90 at 915Mhz. I believe these use different demods, and I've read that rtl_433 defaults to classic for < 868Mhz and minmax for >= 868Mhz. Does it do this when hopping frequencies as well? 

From discussion 3069, zuckschwerdt suggests using the HTTP-API (-F http) but I don't see any documentation on use of that feature.

Any help is greatly appreciated. Thanks.

**Comment by zuckschwerdt** [comment, marked as answer]
One demod is selected at startup and not changed again. The `-Y minmax` should also work for most 433 MHz devices.
Also try with `-s 250k` and `-s 1024k` to which works better for both devices.

**Reply by jhkubs** [reply]
Thank you for the quick reply! I've been trying to get this working using hertzg's docker image and docker compose. Playing with -s seemed to do the trick I think? I tried a variety of arguments in various orders and finally got the below config to work:
```
services:
  rtl_433:
    image: "hertzg/rtl_433:latest"
    container_name: "rtl_433"
    devices:
      - "/dev/bus/usb/001/004"
    command:
      - '-f915M'
      - '-H30'
      - '-f433.92M'
      - '-H30'
      - "-Fmqtt://mosquitto:1883,retain=1,events=rtl_433[/model][/id]"
      - "-s250k"
```
I now see an update from each device every ~30 seconds.
