### ISSUE TITLE
Auto discovery does not properly decode devices

### ISSUE THREAD

**Issue by invisible999** [merbanan/rtl_433#2397]
I am using rtl_433 and rtl_433_auto_discovery with Home Assistant. 

I see that MQTT explorer sees devices and their properties one this way:
![image](https://user-images.githubusercontent.com/45667495/221247346-c195ab7f-e122-4b4e-92ee-f961521d9ab6.png)

However after auto discovery decodes them, it ends up like this

```
automation_type: trigger
type: button_short_release
subtype: button_1
topic: rtl_433/9b13b3f4-rtl433/devices/Markisol/0/1/channel
platform: mqtt
device:
  identifiers:
    - Markisol-0-1
  name: Markisol-0-1
  model: Markisol
  manufacturer: rtl_433

automation_type: trigger
type: button_short_release
subtype: button_1
topic: rtl_433/9b13b3f4-rtl433/devices/Regency-Remote/7/channel
platform: mqtt
device:
  identifiers:
    - Regency-Remote-7
  name: Regency-Remote-7
  model: Regency-Remote
  manufacturer: rtl_433
  ```
And honda car remote does not come with any properties after decoding.
  
  ```
 "device": {
      "id": "fee23ea4e674ee8a119d67aebbbd294a",
      "name": "Honda-CarRemote-65535",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "device_class": null,
          "disabled_by": "integration",
          "disabled": true,
          "entity_category": "diagnostic",
          "entity_id": "sensor.honda_carremote_65535_utc",
          "icon": null,
          "original_device_class": "timestamp",
          "original_icon": "mdi:clock-in",
          "state": null,
          "unit_of_measurement": null
        }
      ]
    },
    "mqtt_debug_info": {
      "entities": [],
      "triggers": []
    }
```

I have seen a number of decoding errors with other devices as well, some temp sensors showing outside temperature as 670F. Well, guess we are living on the surface of Venus...
