### ISSUE TITLE
rtl_433_mqtt_hass.py creates devices with "manufacturer": "rtl_433"

### ISSUE THREAD

**Issue by fallenpegasus** [merbanan/rtl_433#2622]
For example, for one of the entities it creates for me

```
device:
  identifiers:
    - Acurite-515-50
  name: Acurite-515-50
  model: Acurite-515
  manufacturer: rtl_433
```

should be

```
device:
  identifiers:
    - Acurite-515-50
  name: Acurite-515-50
  model: 515
  manufacturer: Acurite
```
