### ISSUE TITLE
Support for sensors with `state` keys

### ISSUE THREAD

**Issue by digitaltopo** [merbanan/rtl_433#2965]
I have several sensors that show up fine on autodiscovery, but unfortunately the primary key used for the sensor is not in the list:
https://github.com/pbkhrv/rtl_433-hass-addons/tree/main/rtl_433_mqtt_autodiscovery#what-sensorsdevices-does-this-script-support

My sensors look like this:
```
time = 2024-06-09 22:15:58
id = 309952
channel = 8
event = 128
state = open
contact_open = 1
reed_open = 0
alarm = 0
tamper = 0
battery_ok = 1
heartbeat = 0
mic = CRC
```

I'd like to request that the `state` key is added to the supported list. Other keys that would be helpful are `contact_open`, and `reed_open`, but those are generally redundant of `state`.

I'm not sure how to get these added, or what the best way to do this would be. I'm open to adding these manually as well, but I'm lacking a bit of understanding on how 'discovery' should work here. If I manually add mqtt sensors, do I not need to use autodiscovery (https://github.com/pbkhrv/rtl_433-hass-addons/tree/main/rtl_433_mqtt_autodiscovery#what-do-i-do-if-my-sensor-is-not-supported)? 

Thanks for any help on this!

**Comment by gdt** [comment]
You have filed an issue in the rtl_433 repo.   for that, you should be reading rtl_433_mqtt_relay and rtl4_433_mqtt_hass in examples.  You  may wish to modify them.

If a hass addon is not doing what you want, and you don't want to start reading python code here and using your own version, that should be addressed to that addons tracker.

**Comment by gdt** [comment]
I set the feedback tag to ask you to convert this into  an issue that is about the contents of the rtl_433 repo. (if that's what you want to do vs closing and bringing it up with the addon).

**Comment by rct** [comment]
That looks somewhat like the Honeywell/2GIG/etc. family of security sensors. You probably want to define a binary_sensor based off of contact_open. 

My advice is not to use autodiscovery but to instead use manual MQTT configuration. There are two many things that autodiscovery doesn't know.  Some sensors may use reed_open or alarm for the bit you are interested in.  I like being able to set the device class to door, window, motion, etc. but have it defined as data someplace outside of home assistant's config_json files.

I wound up defining all my sensors in a YAML file and then defined a Jinja2 template (same templating as home assistant) for the MQTT configuration.  I process about 30 security sensors this way. If I need to update something I usually just need to change the template and run my script. 

```
honeywell_sensors:
- esn: 123456
  name: "Front Door"
  type: "door"
  model: "Honeywell 5800mini"
  area: "Foyer"
  description: "Main Entrance Active Door"
  model_comment: "4th 5800mini"
  zone: 1


- esn: 654321
  name: "Guest Bedroom Window"
  type: "Window"
  model: "Versa Mini"
  manufacturer: "Versa"
  area: "Guest Bedroom"
  description: "Guest Bedroom East Window"
  model_comment: "Versa Mini, 1st from 2nd batch"
  channel: 10
  rtl_433_contact_field: "reed_open"
  zone: 18
```

This is what the template file looks like.  It's quick and dirty so it defined everything for 1 sensor in 1 file. 

```
---
#
# Test Honeywell Security 5800 jinja template.

mqtt:
  binary_sensor:
    - name: "{{ contact_short_name | title }}"  # TODO "Door"
      object_id: "{{ device_name_safe + '_' + contact_short_name }}" # TODO "front_door_contact" 
      unique_id: "{{ device_unique_id + '_' + contact_short_name }}" # "rtl_433_honeywell_123456_contact"
      state_topic: "{{ device_topic + '/' + contact_sub_topic }}"    # "rtl_433/+/devices/Honeywell-Security/8/123456/contact_open"
      payload_on: 1 # open
      payload_off: 0 # closed
      device_class: "{{ device_primary_class }}"
      force_update: true # Needed?
      expire_after: "{{ device_unavailable_seconds }}"
      device:
        name: "{{ device_name_pretty }}" # "Front Door Sensor"
        model: "{{ device_model }}"     # "5800 Mini"
        manufacturer: "{{ device_manufacturer }}"   # "Honeywell"
        identifiers: "{{ device_unique_id }}" # "rtl_433_honeywell_123456"
        suggested_area: "{{ device_area }}"   # "Foyer"

    - name: "Tamper"
      object_id: "{{ device_name_safe + '_tamper' }}" # "front_door_sensor_tamper"
      unique_id: "{{ device_unique_id + '_tamper' }}" # "rtl_433_honeywell_123456_tamper"
      state_topic: "{{ device_topic + '/tamper' }}"   # "rtl_433/+/devices/Honeywell-Security/8/123456/tamper"
      payload_on: 1 # open
      payload_off: 0 # closed
      device_class: safety
      force_update: true # Needed?
      expire_after: "{{ device_unavailable_seconds }}"
      device:
        identifiers: "{{ device_unique_id }}"

    # Event or Heartbeat, inverted to make event == True
    # TODO - should this be considered a diagnostic entity?
    - name: "Event"
      object_id: "{{ device_name_safe + '_event' }}" # "front_door_sensor_event"
      unique_id: "{{ device_unique_id + '_event' }}" #"rtl_433_honeywell_123456_event"
      state_topic: "{{ device_topic + '/heartbeat' }}"   # "rtl_433/+/devices/Honeywell-Security/8/123456/heartbeat"
      payload_on: 0 # 0 == event
      payload_off: 1 # 1 == heartbeat
      force_update: true # Needed?
      expire_after: "{{ device_unavailable_seconds }}"
      device:
        identifiers: "{{ device_unique_id }}"

  sensor:
    # Device undecoded status byte for diagnostic purposes
    # Honeywell-Security misnamed as "event", should be renamed in decoder
    - name: "Status"
      object_id: "{{ device_name_safe + '_status' }}" # "front_door_sensor_status"
      unique_id: "{{ device_unique_id + '_status' }}" # "rtl_433_honeywell_123456_event" 
      state_topic: "{{ device_topic + '/event' }}"   # "rtl_433/+/devices/Honeywell-Security/8/123456/event"
      force_update: true # Needed?
      expire_after: "{{ device_unavailable_seconds }}"
      entity_category: diagnostic
      # todo eventually should be disabled by default?
      device:
        identifiers: "{{ device_unique_id }}"

# TODO Everything below this line are generic rtl_433 sensors
    - name: "Battery"
      object_id: "{{ device_name_safe + '_battery' }}" # "front_door_sensor_battery"
      unique_id: "{{ device_unique_id + '_battery' }}" # "rtl_433_honeywell_123456_battery"
      state_topic: "{{ device_topic + '/battery_ok' }}"   # "rtl_433/+/devices/Honeywell-Security/8/123456/battery_ok"
      value_template: "{{ '{{' }} float(value|int) * 99 + 1 }}"
      device_class: battery
      unit_of_measurement: "%"
      force_update: true # Needed?
      expire_after: "{{ device_unavailable_seconds }}"
      entity_category: diagnostic
      device:
        identifiers: "{{ device_unique_id }}"

    - name: "RSSI"
      object_id: "{{ device_name_safe + '_rssi' }}" # "front_door_sensor_rssi"
      unique_id: "{{ device_unique_id + '_rssi' }}" # "rtl_433_honeywell_123456_rssi"
      state_topic: "{{ device_topic + '/rssi' }}" # "rtl_433/+/devices/Honeywell-Security/8/123456/rssi"
      value_template: "{{ '{{' }} value|float|round(2) }}"
      unit_of_measurement: "dB"
      device_class: signal_strength
      force_update: true # Needed?
      expire_after: "{{ device_unavailable_seconds }}"
      entity_category: diagnostic
      # todo eventually should be disabled by default?
      device:
        identifiers: "{{ device_unique_id }}"

    - name: "SNR"
      object_id: "{{ device_name_safe + '_snr' }}" # "front_door_sensor_snr"
      unique_id: "{{ device_unique_id + '_snr' }}" # "rtl_433_honeywell_123456_snr"
      state_topic: "{{ device_topic + '/snr' }}"   # "rtl_433/+/devices/Honeywell-Security/8/123456/snr"
      value_template: "{{ '{{' }} value|float|round(2) }}"
      unit_of_measurement: "dB"
      device_class: signal_strength
      force_update: true # Needed?
      expire_after: "{{ device_unavailable_seconds }}"
      entity_category: diagnostic
      # todo eventually should be disabled by default?
      device:
        identifiers: "{{ device_unique_id }}"

    - name: "noise"
      object_id: "{{ device_name_safe + '_noise' }}" # "front_door_sensor_noise"
      unique_id: "{{ device_unique_id + '_noise' }}" # "rtl_433_honeywell_123456_noise"
      state_topic: "{{ device_topic + '/noise' }}"   # "rtl_433/+/devices/Honeywell-Security/8/123456/noise"
      value_template: "{{ '{{' }} value|float|round(2) }}"
      unit_of_measurement: "dB"
      device_class: signal_strength
      force_update: true # Needed?
      expire_after: "{{ device_unavailable_seconds }}"
      entity_category: diagnostic
      enabled_by_default: false
      # todo eventually should be disabled by default?
      device:
        identifiers: "{{ device_unique_id }}"
```
